"""
Ingest DDoS Attack Simulator Logs into Training Dataset
Converts attack simulation logs to labeled training data for model retraining.
"""

import os
import sys
import csv
import json
import pandas as pd
from datetime import datetime, timedelta
from pathlib import Path

# ─────────────────────────────────────────────────────────────────────────────
# Attack Type Label Mapping
# ─────────────────────────────────────────────────────────────────────────────

ATTACK_TYPE_LABELS = {
    "SYN_FLOOD": 1,
    "UDP_FLOOD": 1,
    "ACK_FLOOD": 1,
    "HTTP_FLOOD": 1,
    "SLOWLORIS": 1,
    "PORT_SCAN": 1,
    "NORMAL": 0
}

ATTACK_CATEGORIES = {
    "SYN_FLOOD": "Connection Attack",
    "UDP_FLOOD": "Volumetric Attack",
    "ACK_FLOOD": "Reflection Attack",
    "HTTP_FLOOD": "Application Layer Attack",
    "SLOWLORIS": "Resource Starvation",
    "PORT_SCAN": "Reconnaissance"
}

# ─────────────────────────────────────────────────────────────────────────────
# Log Ingestion
# ─────────────────────────────────────────────────────────────────────────────

def read_attack_log(log_file: str) -> pd.DataFrame:
    """Read the CSV log generated by ddos_attack_simulator.py"""
    if not os.path.exists(log_file):
        raise FileNotFoundError(f"Log file not found: {log_file}")

    df = pd.read_csv(log_file)
    print(f"[✓] Loaded {len(df)} attack records from {log_file}")
    return df

def create_training_records(attack_log: pd.DataFrame) -> list:
    """
    Convert attack logs to training records.
    Each attack generates multiple flow-level records.
    """
    training_records = []

    for idx, row in attack_log.iterrows():
        attack_type = row["attack_type"]
        timestamp = row["timestamp"]
        src_ip = row["src_ip"]
        dst_ip = row["dst_ip"]
        packets_sent = int(row["packets_sent"])
        duration_sec = float(row["duration_sec"])
        intensity = row["intensity"]
        pps = float(row["pps"])

        # Create flow-level labels from packet-level statistics
        # Simulate 5 flows per attack window
        num_flows = max(1, packets_sent // 100)

        for flow_id in range(min(5, num_flows)):
            # Distribute packets across flows
            flow_packets = packets_sent // 5
            flow_bytes = flow_packets * random.randint(64, 1500)

            record = {
                "timestamp": timestamp,
                "attack_type": attack_type,
                "attack_category": ATTACK_CATEGORIES.get(attack_type, "Unknown"),
                "label": ATTACK_TYPE_LABELS.get(attack_type, 0),
                "src_ip": src_ip,
                "dst_ip": dst_ip,
                "src_port": random.randint(1024, 65535),
                "dst_port": random.choice([22, 80, 443, 8080]) if attack_type != "UDP_FLOOD" else random.randint(1, 65535),
                "protocol": "TCP" if attack_type != "UDP_FLOOD" else "UDP",
                "packet_count": flow_packets,
                "byte_count": flow_bytes,
                "duration_sec": duration_sec,
                "packet_rate": flow_packets / max(duration_sec, 1),
                "byte_rate": flow_bytes / max(duration_sec, 1),
                "intensity": intensity,
                "pps": pps,
                "flow_id": f"{src_ip}:{flow_id}"
            }
            training_records.append(record)

    print(f"[✓] Generated {len(training_records)} flow-level training records")
    return training_records

def save_training_csv(records: list, output_file: str = "training_data_with_labels.csv"):
    """Save training records to CSV."""
    if not records:
        print("[!] No records to save")
        return

    df = pd.DataFrame(records)
    df.to_csv(output_file, index=False)
    print(f"[✓] Saved labeled training data to: {output_file}")
    print(f"    Columns: {list(df.columns)}")
    print(f"    Attack records: {(df['label'] == 1).sum()}")
    print(f"    Normal records: {(df['label'] == 0).sum()}")
    return output_file

def generate_training_report(records: list) -> dict:
    """Generate statistics about the training data."""
    df = pd.DataFrame(records)

    report = {
        "total_records": len(df),
        "attack_records": int((df['label'] == 1).sum()),
        "normal_records": int((df['label'] == 0).sum()),
        "attack_types": df['attack_type'].value_counts().to_dict(),
        "intensities": df['intensity'].value_counts().to_dict(),
        "avg_packet_rate": float(df['packet_rate'].mean()),
        "avg_byte_rate": float(df['byte_rate'].mean()),
        "time_range": {
            "start": str(df['timestamp'].min()),
            "end": str(df['timestamp'].max())
        }
    }
    return report

def save_training_report(report: dict, output_file: str = "training_report.json"):
    """Save training report as JSON."""
    with open(output_file, 'w') as f:
        json.dump(report, f, indent=2)
    print(f"\n[✓] Training report saved to: {output_file}")

def print_training_report(report: dict):
    """Print training report summary."""
    print("\n" + "=" * 80)
    print("TRAINING DATA SUMMARY")
    print("=" * 80)
    print(f"Total Records:         {report['total_records']}")
    print(f"Attack Records:        {report['attack_records']} ({100*report['attack_records']/max(report['total_records'],1):.1f}%)")
    print(f"Normal Records:        {report['normal_records']} ({100*report['normal_records']/max(report['total_records'],1):.1f}%)")
    print(f"\nAttack Breakdown:")
    for attack_type, count in report['attack_types'].items():
        print(f"  {attack_type:20s}: {count:4d} ({100*count/max(report['attack_records'],1):.1f}%)")
    print(f"\nIntensity Breakdown:")
    for intensity, count in report['intensities'].items():
        print(f"  {intensity:10s}: {count:4d} ({100*count/report['total_records']:.1f}%)")
    print(f"\nStatistics:")
    print(f"  Avg Packet Rate:     {report['avg_packet_rate']:.1f} pps")
    print(f"  Avg Byte Rate:       {report['avg_byte_rate']:.1f} bytes/sec")
    print(f"  Time Range:          {report['time_range']['start']} to {report['time_range']['end']}")
    print("=" * 80 + "\n")

# ─────────────────────────────────────────────────────────────────────────────
# Integration with Existing Training Pipeline
# ─────────────────────────────────────────────────────────────────────────────

def integrate_with_training_pipeline(training_csv: str, output_dir: str = None):
    """
    Optionally integrate this labeled data with the main training pipeline.
    """
    if output_dir is None:
        output_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "datasets", "attack_logs"))

    os.makedirs(output_dir, exist_ok=True)

    # Copy training file to datasets directory
    import shutil
    dest = os.path.join(output_dir, os.path.basename(training_csv))
    shutil.copy(training_csv, dest)

    print(f"[✓] Integrated training data into pipeline:")
    print(f"    {dest}")
    print(f"\nNext steps:")
    print(f"  1. Retrain models: python project/backend/train_models.py")
    print(f"  2. Test detection: python project/backend/api.py")

# ─────────────────────────────────────────────────────────────────────────────
# Main CLI
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import argparse
    import random

    parser = argparse.ArgumentParser(
        description="Convert DDoS Attack Simulator logs to labeled training data"
    )
    parser.add_argument("log_file", help="Path to ddos_attack_simulator.py output CSV")
    parser.add_argument("--output", default="training_data_with_labels.csv",
                       help="Output CSV filename (default: training_data_with_labels.csv)")
    parser.add_argument("--report", default="training_report.json",
                       help="Output report JSON (default: training_report.json)")
    parser.add_argument("--integrate", action="store_true",
                       help="Copy to datasets/ for training pipeline")

    args = parser.parse_args()

    print("\n" + "=" * 80)
    print("ATTACK LOG INGESTION")
    print("=" * 80 + "\n")

    try:
        # Read attack log
        attack_log = read_attack_log(args.log_file)

        # Create training records
        records = create_training_records(attack_log)

        # Save as CSV
        output_csv = save_training_csv(records, args.output)

        # Generate and save report
        report = generate_training_report(records)
        save_training_report(report, args.report)

        # Print summary
        print_training_report(report)

        # Optionally integrate with training pipeline
        if args.integrate:
            integrate_with_training_pipeline(output_csv)

        print("[✓] Attack log ingestion complete!")

    except Exception as e:
        print(f"[ERROR] {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
